In [1]:
import numpy as np


def read_pts_file(file_path):
    points = np.loadtxt(file_path)
    return points

file_path = 'temp_file.pts'
point_cloud = read_pts_file(file_path)
print(point_cloud)


[[  2.634485 -24.515221   4.808706]
 [  2.075485 -24.685221   3.582706]
 [  2.617485 -24.238221   4.068706]
 ...
 [ 13.213485 -22.531221   7.294706]
 [ 13.015485 -21.558221   7.307706]
 [ 12.593485 -21.674221   7.      ]]


In [2]:
!pip install open3d

     |████████████████████████████    | 348.5 MB 86.5 MB/s eta 0:00:01

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



     |████████████████████████████████| 399.7 MB 33 kB/s 
     |████████████████████████████████| 7.5 MB 58.7 MB/s eta 0:00:01
     |████████████████████████████████| 101 kB 840 kB/s eta 0:00:01


In [3]:
import open3d as o3d


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [5]:
import open3d as o3d

def read_pts_with_open3d(file_path):
    point_cloud = o3d.io.read_point_cloud(file_path, format='xyz')
    return point_cloud

file_path = 'temp_file.pts'
pcd = read_pts_with_open3d(file_path)

# Optionally save the point cloud to a file
o3d.io.write_point_cloud("output.ply", pcd)  # Save as PLY or another format
print("Point cloud saved to output.ply")


Point cloud saved to output.ply


In [ ]:
import open3d as o3d
import numpy as np

# Load the point cloud
pcd = o3d.io.read_point_cloud("ou.ply")  # or .pts

# Sample a subset of points
points = np.asarray(pcd.points)
if points.shape[0] > 10000:  # Adjust the number as needed
    indices = np.random.choice(points.shape[0], size=10000, replace=False)
    sampled_points = points[indices]
    pcd.points = o3d.utility.Vector3dVector(sampled_points)

# Visualize
o3d.visualization.draw_geometries([pcd], window_name="Open3D WebVisualizer")
import open3d as o3d

# Load the point cloud
pcd = o3d.io.read_point_cloud("output.ply")  # or .pts

# Start the web visualizer
vis = o3d.visualization.Visualizer()
vis.create_window(window_name="Open3D WebVisualizer", width=800, height=600, visible=True)
vis.add_geometry(pcd)
vis.run()
vis.destroy_window()



Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
